-- Kumon Iligan Operations Platform — Seed Script
-- TODO: Populate before go-live using Nina's existing student/family spreadsheet
--
-- Migration plan:
--   1. Export Nina's current spreadsheet to CSV (students, families)
--   2. Run import script: scripts/import-students.ts (to be written)
--   3. Seed initial payment_periods for current month
--   4. Assign students to teachers via student_teacher_assignments
--
-- Tables to seed:
--   branches        — add Kumon Iligan branch record
--   users           — admin and teacher accounts (via Supabase Auth invite, not seed)
--   families        — guardian records from CSV
--   students        — student records from CSV, linked to families
--   student_teacher_assignments — assign each student to their teacher
--   payment_periods — generate current month periods for all active students

-- See docs/prd.md Section 11 (Migration Strategy) for full plan.
